name: Node.js CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Go to project directory
        run: cd auth-service
        
      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        working-directory: ./auth-service
        with:
          node-version: 20
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: ./auth-service

      # Step 4: Run tests
      - name: Run tests
        run: npm test
        working-directory: ./auth-service

      # Step 5: Build the project
      - name: Build the project
        run: npm run build
        working-directory: ./auth-service