name: Python FastAPI CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run Formating and Linting
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Step 3: Install dependencies
      - name: Install dependencies
        working-directory: order-booking-service  # Set the working directory
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .[dev] # pytest is in requirements.txt, so it's installed here

      # Step 4: Run Ruff (Linter)
      - name: Run Ruff
        working-directory: order-booking-service  # Set the working directory
        run: ruff check .

      # Step 5: Run Black (Code Formatter Check)
      - name: Run Black
        working-directory: order-booking-service  # Set the working directory
        run: black --check .

      # Step 6: Run isort (Import Sorter Check)
      - name: Run isort
        working-directory: order-booking-service  # Set the working directory
        run: isort . --check-only

      # Step 7: Run Pytest
      - name: Run Pytest
        working-directory: order-booking-service  # Set the working directory
        run: pytest
